package Jframe;

import tareaestrucutradatos.*;

public class ArbolJFrame extends javax.swing.JFrame {
    
    Arbol arbol; 
    
    public ArbolJFrame() {
        initComponents();
        this.setTitle("Arbol");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonEXIT = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setText("/");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 30, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 30, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 30, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 30, 30));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 30, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 30, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 30, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 30, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 30, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 30, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 30, -1));

        jButton1.setText("PreOrden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jButton2.setText("InOrden");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 80, -1));

        jButton3.setText("PosOrden");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel2.setMaximumSize(new java.awt.Dimension(234, 216));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 240, 120));

        jButton9.setText("Datos de Prueba");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 150, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 30, 10));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setText("\\");
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 20, 30));

            jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            jLabel6.setText("/");
            getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 10, 30));

            jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            jLabel7.setText("  / ");
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, -1));

            jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
            jLabel8.setText("   \\");
                getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 40, -1));

                jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                jLabel9.setText("\\");
                    getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 20, 30));

                    jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                    jLabel10.setText("\\");
                        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, 30));

                        jLabel11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                        jLabel11.setText("\\");
                            getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 20, 30));

                            jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel12.setText("/");
                            getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 10, 30));

                            jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel14.setText("/");
                            getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 10, 30));

                            jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel15.setText("/");
                            getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 10, 30));

                            jLabel16.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel16.setText("/");
                            getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 10, 30));

                            jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel17.setText("/");
                            getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 10, 30));

                            jLabel18.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                            jLabel18.setText("\\");
                                getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 20, 30));

                                jButtonEXIT.setText("EXIT");
                                jButtonEXIT.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButtonEXITActionPerformed(evt);
                                    }
                                });
                                getContentPane().add(jButtonEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

                                jButtonRegresar.setText("Regresar");
                                jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButtonRegresarActionPerformed(evt);
                                    }
                                });
                                getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

                                jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
                                jLabel1.setText("Arbol");
                                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

                                pack();
                            }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarArbol();
        jTextArea1.setText(arbol.preOrden(arbol.getRaiz()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarArbol();
        jTextArea1.setText(arbol.inOrden(arbol.getRaiz()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cargarArbol();
        jTextArea1.setText(arbol.posOrden(arbol.getRaiz()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextField1.setText("1");
        jTextField2.setText("2");
        jTextField3.setText("3");
        jTextField4.setText("4");
        jTextField5.setText("5");
        jTextField6.setText("6");
        jTextField7.setText("7");
        jTextField8.setText("8");
        jTextField9.setText("9");
        jTextField10.setText("10");
        jTextField11.setText("11");
        jTextField12.setText("12");
        jTextField13.setText("13");
        jTextField14.setText("14");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonEXITActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // Regresa al INicio
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolJFrame().setVisible(true);
            }
        });
    }

    public void cargarArbol(){
        arbol=new Arbol(jTextField1.getText());
        //Nivel 2
        arbol.insertarIzquierda(jTextField2.getText(), arbol.getRaiz());
        arbol.insertarDerecha(jTextField3.getText(), arbol.getRaiz());
        //Nivel 3
        arbol.insertarIzquierda(jTextField4.getText(), arbol.getRaiz().getIzquierda());
        arbol.insertarDerecha(jTextField5.getText(), arbol.getRaiz().getIzquierda());
        arbol.insertarIzquierda(jTextField6.getText(), arbol.getRaiz().getDerecha());
        //Nivel 4
        arbol.insertarDerecha(jTextField7.getText(), arbol.getRaiz().getIzquierda().getIzquierda());
        arbol.insertarIzquierda(jTextField8.getText(), arbol.getRaiz().getIzquierda().getDerecha());
        arbol.insertarDerecha(jTextField9.getText(), arbol.getRaiz().getIzquierda().getDerecha());
        arbol.insertarIzquierda(jTextField10.getText(), arbol.getRaiz().getDerecha().getIzquierda());
        arbol.insertarDerecha(jTextField11.getText(), arbol.getRaiz().getDerecha().getIzquierda());
        //Nivel 5
        arbol.insertarIzquierda(jTextField12.getText(), arbol.getRaiz().getIzquierda().getDerecha().getIzquierda());
        arbol.insertarIzquierda(jTextField13.getText(), arbol.getRaiz().getDerecha().getIzquierda().getIzquierda());
        arbol.insertarDerecha(jTextField14.getText(), arbol.getRaiz().getDerecha().getIzquierda().getIzquierda());
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonEXIT;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
