/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tareaestrucutradatos.Listas;

/**
 *
 * @author ANDY
 */
public class ListasDobles extends javax.swing.JFrame {
    private ImageIcon ima;
    private Icon icono;
    /**
     * Creates new form ListasDobles
     */
    public ListasDobles() {
        initComponents();
        this.setTitle("Listas Dobles");
        this.setLocationRelativeTo(null);
        
        //imagen
        this.ImagenInicio(this.jLabel2, "src/Imagenes/listaDobleEnlace.png");
    }
    //imagen Metodo

    private void ImagenInicio(JLabel imagen, String ruta) {
        this.ima = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.ima.getImage().getScaledInstance(imagen.getWidth(),
                imagen.getHeight(),
                Image.SCALE_DEFAULT));
        imagen.setIcon(this.icono);
        this.repaint();
    }
//lista doble ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
    Listas lista = new Listas();
//lista doble ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDisco = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jButtonNodoInicio = new javax.swing.JButton();
        jButtonNodoFinal = new javax.swing.JButton();
        jButtonMostrarInicioFin = new javax.swing.JButton();
        jButtonMostrarFinInicio = new javax.swing.JButton();
        jButtonEliminarInicio = new javax.swing.JButton();
        jButtonEliminarFinal = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setText("Lista doble");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" 1-Introduce un numero\n 2-Escoje entre las opciones");

        jLabelDisco.setText("Introduce numero:");

        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        jButtonNodoInicio.setText("Agrega un Nodo al Inicio");
        jButtonNodoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNodoInicioActionPerformed(evt);
            }
        });

        jButtonNodoFinal.setText("Agregar un Nodo al Final");
        jButtonNodoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNodoFinalActionPerformed(evt);
            }
        });

        jButtonMostrarInicioFin.setText("Mostrar Lista Inicio a Fin");
        jButtonMostrarInicioFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarInicioFinActionPerformed(evt);
            }
        });

        jButtonMostrarFinInicio.setText("Mostrar Lista Fin a Inicio");
        jButtonMostrarFinInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarFinInicioActionPerformed(evt);
            }
        });

        jButtonEliminarInicio.setText("Eliminar Inicio");
        jButtonEliminarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarInicioActionPerformed(evt);
            }
        });

        jButtonEliminarFinal.setText("Eliminar Final");
        jButtonEliminarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFinalActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabelDisco))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButtonSalir)
                                .addGap(61, 61, 61)
                                .addComponent(jButtonRegresar)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminarFinal)
                    .addComponent(jButtonEliminarInicio)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNodoInicio)
                            .addComponent(jButtonNodoFinal))
                        .addComponent(jButtonMostrarInicioFin, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonMostrarFinInicio, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButtonBuscar))
                .addGap(13, 13, 13))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalir)
                            .addComponent(jButtonRegresar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNodoInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNodoFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarInicioFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarFinInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void jButtonNodoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNodoInicioActionPerformed
     //Agrega el numero al inicio
        int numero = Integer.parseInt(jTextNumero.getText());
       lista.addInicio(numero);
       JOptionPane.showMessageDialog(null, "Numero Ingresado");
       jTextNumero.setText(""); // limpiar casilla
       jButtonNodoInicio.setEnabled(false); // bloquer boton
    }//GEN-LAST:event_jButtonNodoInicioActionPerformed

    private void jButtonNodoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNodoFinalActionPerformed
       jButtonNodoInicio.setEnabled(false); //bloquar boton
        //Agrega el numero al final
        int numero = Integer.parseInt(jTextNumero.getText());
       lista.addFinal(numero);
       JOptionPane.showMessageDialog(null, "Numero Ingresado");
       jTextNumero.setText(""); // limpiar casilla
      
    }//GEN-LAST:event_jButtonNodoFinalActionPerformed

    private void jButtonMostrarInicioFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarInicioFinActionPerformed
    
        //Mostrar Inicio al Fin 
        if(!lista.vacio()){
                          lista.mostrarIaF();
                      }  else{
                               JOptionPane.showMessageDialog(null, "Lista vacia");
         }
    }//GEN-LAST:event_jButtonMostrarInicioFinActionPerformed

    private void jButtonMostrarFinInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarFinInicioActionPerformed
        // Mostrar Fin a Inicio
        if(!lista.vacio()){
                          lista.mostrarFaI();
                      }  else{
                         JOptionPane.showMessageDialog(null, "Lista vacia");
                      }
    }//GEN-LAST:event_jButtonMostrarFinInicioActionPerformed

    private void jButtonEliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarInicioActionPerformed
        // Elimina el Inicio
         
         if(!lista.vacio()){
           
                       lista.QuitarInicio();
                            JOptionPane.showMessageDialog(null,"Eliminado el nodo del Inicio");
                        }else{
                            JOptionPane.showMessageDialog(null, "No hay nodos AUN",
                                  "Lista vacia",JOptionPane.INFORMATION_MESSAGE);
                        }
    }//GEN-LAST:event_jButtonEliminarInicioActionPerformed

    private void jButtonEliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFinalActionPerformed
        //Eliminar fin
       
        if(!lista.vacio()){
                          lista.QuitarFin();
                            JOptionPane.showMessageDialog(null, "Eliminado el nodo del final");
                        }else{
                            JOptionPane.showMessageDialog(null, "No hay nodos AUN",
                                  "Lista vacia",JOptionPane.INFORMATION_MESSAGE);
                        }
    }//GEN-LAST:event_jButtonEliminarFinalActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       lista.Busqueda();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
         Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListasDobles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListasDobles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListasDobles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListasDobles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListasDobles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminarFinal;
    private javax.swing.JButton jButtonEliminarInicio;
    private javax.swing.JButton jButtonMostrarFinInicio;
    private javax.swing.JButton jButtonMostrarInicioFin;
    private javax.swing.JButton jButtonNodoFinal;
    private javax.swing.JButton jButtonNodoInicio;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDisco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextNumero;
    // End of variables declaration//GEN-END:variables
}
