/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tareaestrucutradatos.ListaSimple;

/**
 *
 * @author ANDY
 */
public class Listas extends javax.swing.JFrame {
    private ImageIcon ima;
    private Icon icono;
    /**
     * Creates new form Listas
     */
    public Listas() {
        initComponents();
         this.setTitle("Listas Simple");
        this.setLocationRelativeTo(null);
        
           //imagen
        this.ImagenInicio(this.jLabelLS, "src/Imagenes/ALUMNOS.png");
    }
      //imagen Metodo

    private void ImagenInicio(JLabel imagen, String ruta) {
        this.ima = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.ima.getImage().getScaledInstance(imagen.getWidth(),
                imagen.getHeight(),
                Image.SCALE_DEFAULT));
        imagen.setIcon(this.icono);
        this.repaint();
    }
    //lista simple ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
ListaSimple lista = new ListaSimple();
//lista simple ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDisco2 = new javax.swing.JLabel();
        jTextNumero2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDisco = new javax.swing.JLabel();
        jTextAlumno = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelDisco1 = new javax.swing.JLabel();
        jTextAsistenncia = new javax.swing.JTextField();
        jLabelDisco3 = new javax.swing.JLabel();
        jTextNumControl = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminarFinal = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jButtonEliminarInicio = new javax.swing.JButton();
        jLabelLS = new javax.swing.JLabel();

        jLabelDisco2.setText("Introduce su numero de control:");

        jTextNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumero2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setText("Lista simple");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" En un colegio se hace una lista\n de los estudiante que asistieron\n a clases, en donde se muestra \n el nombre del estudiante, su \n numero de control y su asistencia.");

        jLabelDisco.setText("Introduce el nombre del estudiante:");

        jTextAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumnoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jLabelDisco1.setText("Introduce su numero de control:");

        jTextAsistenncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAsistennciaActionPerformed(evt);
            }
        });

        jLabelDisco3.setText("Asistio a clases (S/N):");

        jTextNumControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumControlActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEliminarFinal.setText("Eliminar el Final");
        jButtonEliminarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFinalActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonEliminarInicio.setText("Eliminar el Inicio");
        jButtonEliminarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelDisco1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminarFinal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonAgregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscar)
                            .addComponent(jButtonMostrar))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDisco3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextAsistenncia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDisco)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonEliminarInicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSalir)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonRegresar))
                            .addComponent(jLabelLS, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMostrar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEliminarFinal)
                            .addGap(38, 38, 38))
                        .addComponent(jButtonEliminarInicio, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDisco1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDisco3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAsistenncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonRegresar))
                .addGap(28, 28, 28)
                .addComponent(jLabelLS, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumnoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextAsistennciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAsistennciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAsistennciaActionPerformed

    private void jTextNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumero2ActionPerformed

    private void jTextNumControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumControlActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Buscando Alumno");
        String nombre= jTextAlumno.getText();
        int numControl=Integer.parseInt(jTextNumControl.getText());
        char Asistencia = jTextAsistenncia.getText().charAt(0);
         
        if(lista.Buscar(nombre, numControl, Asistencia)==true){
            String elemento ="Alumno  encontrado: \nNombre: "+nombre+"\nNum. Control: "+ numControl+"\nAsistencia: "+Asistencia;
            JOptionPane.showMessageDialog(this, elemento);
        }
            String elemento ="Alumno NO  encontrado: \nNombre: "+nombre+"\nNum. Control: "+ numControl+"\nAsistencia: "+Asistencia;
            JOptionPane.showMessageDialog(this, elemento);
            
            jTextAlumno.setText(null);
        jTextNumControl.setText(null);
        jTextAsistenncia.setText(null);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        String nombre= jTextAlumno.getText();
        int numControl=Integer.parseInt(jTextNumControl.getText());
        char Asistencia = jTextAsistenncia.getText().charAt(0);
        lista.Agregar(nombre, numControl, Asistencia);
        JOptionPane.showMessageDialog(null, "Se agrego al alumno");
        jTextAlumno.setText(null);
        jTextNumControl.setText(null);
        jTextAsistenncia.setText(null);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        // TODO add your handling code here:
        lista.Mostrar();
        
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonEliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFinalActionPerformed
        // TODO add your handling code here:
        lista.EliminarF();
    }//GEN-LAST:event_jButtonEliminarFinalActionPerformed

    private void jButtonEliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarInicioActionPerformed
        // TODO add your handling code here:
        lista.EliminarI();
    }//GEN-LAST:event_jButtonEliminarInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminarFinal;
    private javax.swing.JButton jButtonEliminarInicio;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDisco;
    private javax.swing.JLabel jLabelDisco1;
    private javax.swing.JLabel jLabelDisco2;
    private javax.swing.JLabel jLabelDisco3;
    private javax.swing.JLabel jLabelLS;
    private javax.swing.JTextField jTextAlumno;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextAsistenncia;
    private javax.swing.JTextField jTextNumControl;
    private javax.swing.JTextField jTextNumero2;
    // End of variables declaration//GEN-END:variables
}
