/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;
//new javax.swing.JPanel();
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File; //
import java.net.URI;

import javafx.application.Platform;//
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;//

import javafx.scene.Scene;//
import javafx.scene.media.Media;//
import javafx.scene.media.MediaPlayer;//
import javafx.scene.media.MediaView;//
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;




/**
 *
 * @author 
 - Andrea Morales Chavez
 - Biomara Valenzuela Godina
 - Karen Adriana Mendoza Aragón
 - Jesús Emanuel Palacios Mendias
 @date 01/12/2022

 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private final JFXPanel jfxPane1 = new JFXPanel();
    
    FondoPanel fondo = new FondoPanel();
    
    public Menu() {
       initComponents();
        createScene();
        this.setTitle("Menu");
        /*
        setResizable(false);
        setLocationRelativeTo(null);
        */
        //Video
       
       jLabel2.setLayout(new BorderLayout());
       jLabel2.add(jfxPane1,BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        
    }

   
    private void createScene() {
Platform.runLater(new Runnable() {
    @Override
    public void run() {
        File file= new File ("src/Imagenes/10 ESTRUCTURAS DE DATOS que TODO programador debe conocer.mp4");
        MediaPlayer oracleVid = new MediaPlayer(
          new Media (file.toURI().toString()) );
       
    //anade el video
    

        jfxPane1.setScene(new Scene(new Group(new MediaView(oracleVid))));
        oracleVid.setVolume(0);
        oracleVid.setCycleCount(MediaPlayer.INDEFINITE);
        oracleVid.play();
        }});
}
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pilas = new javax.swing.JFrame();
        ColasSimples = new javax.swing.JFrame();
        ColasCirculares = new javax.swing.JFrame();
        ListasDobles = new javax.swing.JFrame();
        ListasSimple = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new FondoPanel();
        jVIDEO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPilas = new javax.swing.JMenu();
        jMenuItemPilas = new javax.swing.JMenuItem();
        jPilasMaquina = new javax.swing.JMenuItem();
        MenuListasEnlazadas = new javax.swing.JMenu();
        jMenuItemListasDoblemente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuColas = new javax.swing.JMenu();
        jMenuItemColaCirculare = new javax.swing.JMenuItem();
        jMenuItemColaSimple = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuArbol = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuBinario = new javax.swing.JMenuItem();
        MenuHASH = new javax.swing.JMenuItem();
        MenuSecuencia = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuBurbuja = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuInter = new javax.swing.JMenuItem();

        javax.swing.GroupLayout PilasLayout = new javax.swing.GroupLayout(Pilas.getContentPane());
        Pilas.getContentPane().setLayout(PilasLayout);
        PilasLayout.setHorizontalGroup(
            PilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PilasLayout.setVerticalGroup(
            PilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ColasSimplesLayout = new javax.swing.GroupLayout(ColasSimples.getContentPane());
        ColasSimples.getContentPane().setLayout(ColasSimplesLayout);
        ColasSimplesLayout.setHorizontalGroup(
            ColasSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ColasSimplesLayout.setVerticalGroup(
            ColasSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ColasCircularesLayout = new javax.swing.GroupLayout(ColasCirculares.getContentPane());
        ColasCirculares.getContentPane().setLayout(ColasCircularesLayout);
        ColasCircularesLayout.setHorizontalGroup(
            ColasCircularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ColasCircularesLayout.setVerticalGroup(
            ColasCircularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ListasDoblesLayout = new javax.swing.GroupLayout(ListasDobles.getContentPane());
        ListasDobles.getContentPane().setLayout(ListasDoblesLayout);
        ListasDoblesLayout.setHorizontalGroup(
            ListasDoblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ListasDoblesLayout.setVerticalGroup(
            ListasDoblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ListasSimpleLayout = new javax.swing.GroupLayout(ListasSimple.getContentPane());
        ListasSimple.getContentPane().setLayout(ListasSimpleLayout);
        ListasSimpleLayout.setHorizontalGroup(
            ListasSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ListasSimpleLayout.setVerticalGroup(
            ListasSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVIDEO.setText("Ir al video");
        jVIDEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVIDEOActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Referencia");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jLabel2.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jVIDEO)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonRegresar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jVIDEO))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonRegresar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        MenuPilas.setText("Pilas");

        jMenuItemPilas.setText("Pilas Rockola");
        jMenuItemPilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPilasActionPerformed(evt);
            }
        });
        MenuPilas.add(jMenuItemPilas);

        jPilasMaquina.setText("Pilas Maquina expendedora");
        jPilasMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPilasMaquinaActionPerformed(evt);
            }
        });
        MenuPilas.add(jPilasMaquina);

        jMenuBar1.add(MenuPilas);

        MenuListasEnlazadas.setText("Listas Enlazadas");

        jMenuItemListasDoblemente.setText("Lista Doblemente Enlazada");
        jMenuItemListasDoblemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListasDoblementeActionPerformed(evt);
            }
        });
        MenuListasEnlazadas.add(jMenuItemListasDoblemente);

        jMenuItem1.setText("Lista Simple");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuListasEnlazadas.add(jMenuItem1);

        jMenuBar1.add(MenuListasEnlazadas);

        MenuColas.setText("Colas");

        jMenuItemColaCirculare.setText("Cola de turnos");
        jMenuItemColaCirculare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColaCirculareActionPerformed(evt);
            }
        });
        MenuColas.add(jMenuItemColaCirculare);

        jMenuItemColaSimple.setText("Colas de numeros");
        jMenuItemColaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColaSimpleActionPerformed(evt);
            }
        });
        MenuColas.add(jMenuItemColaSimple);

        jMenuBar1.add(MenuColas);

        jMenu3.setText("Estrucutras NO lineales");

        MenuArbol.setText("Arboles");
        MenuArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArbolActionPerformed(evt);
            }
        });
        jMenu3.add(MenuArbol);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Metodos Busqueda");

        MenuBinario.setText("Binaria");
        MenuBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBinarioActionPerformed(evt);
            }
        });
        jMenu4.add(MenuBinario);

        MenuHASH.setText("HASH");
        MenuHASH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHASHActionPerformed(evt);
            }
        });
        jMenu4.add(MenuHASH);

        MenuSecuencia.setText("Secuencia");
        MenuSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSecuenciaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuSecuencia);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Metodos Ordenamiento");

        MenuBurbuja.setText("Burbuja");
        MenuBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBurbujaActionPerformed(evt);
            }
        });
        jMenu5.add(MenuBurbuja);

        jMenuItem2.setText("Seleccion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        MenuInter.setText("Interseccion");
        MenuInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInterActionPerformed(evt);
            }
        });
        jMenu5.add(MenuInter);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListasDoblementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListasDoblementeActionPerformed
        // TODO add your handling code here:
        ListasDobles lista = new ListasDobles();
        this.setVisible(false);
        lista.setVisible(true);
    }//GEN-LAST:event_jMenuItemListasDoblementeActionPerformed

    private void jMenuItemColaCirculareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColaCirculareActionPerformed
        // TODO add your handling code here:
        ColasJFrame cola = new ColasJFrame ();
        this.setVisible(false);
        cola.setVisible(true);
    }//GEN-LAST:event_jMenuItemColaCirculareActionPerformed

    private void jMenuItemPilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPilasActionPerformed
        //ir al Jframe PilasJframe
        PilasJframe pila = new PilasJframe();
        this.setVisible(false);
        pila.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemPilasActionPerformed

    private void jPilasMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPilasMaquinaActionPerformed
       Pila2 pila = new Pila2();
        this.setVisible(false);
        pila.setVisible(true);
    }//GEN-LAST:event_jPilasMaquinaActionPerformed

    private void jVIDEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVIDEOActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=5Y7T6ubaq04&t=3s"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"No se a podido cargar el video");
        }
    }//GEN-LAST:event_jVIDEOActionPerformed

    private void jMenuItemColaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColaSimpleActionPerformed
        // TODO add your handling code here:
        Colas2 cola = new Colas2();
        this.setVisible(false);
        cola.setVisible(true);
    }//GEN-LAST:event_jMenuItemColaSimpleActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        Estrucutras_Datos abrir= new Estrucutras_Datos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Listas abrir= new Listas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBinarioActionPerformed
        // TODO add your handling code here:
         BusquedaBinaria binario = new BusquedaBinaria();
        this.setVisible(false);
        binario.setVisible(true);
    }//GEN-LAST:event_MenuBinarioActionPerformed

    private void MenuHASHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHASHActionPerformed
        // TODO add your handling code here:
        BusquedaHASH HA = new BusquedaHASH();
        this.setVisible(false);
        HA.setVisible(true);
    }//GEN-LAST:event_MenuHASHActionPerformed

    private void MenuSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSecuenciaActionPerformed
        // TODO add your handling code here:
       BusquedaSecuencial secuencial = new BusquedaSecuencial();
        this.setVisible(false);
        secuencial.setVisible(true); 
    }//GEN-LAST:event_MenuSecuenciaActionPerformed

    private void MenuArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArbolActionPerformed
        // TODO add your handling code here:
        ArbolJFrame Arbol = new ArbolJFrame();
        this.setVisible(false);
        Arbol.setVisible(true); 
    }//GEN-LAST:event_MenuArbolActionPerformed

    private void MenuBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBurbujaActionPerformed
        // TODO add your handling code here:
        Burbuja Burbuja = new Burbuja();
        this.setVisible(false);
        Burbuja.setVisible(true); 
    }//GEN-LAST:event_MenuBurbujaActionPerformed

    private void MenuInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInterActionPerformed
        // TODO add your handling code here:
         Insercion in = new Insercion();
        this.setVisible(false);
        in.setVisible(true); 
    }//GEN-LAST:event_MenuInterActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Ordenamiento seleccion = new Ordenamiento();
        this.setVisible(false);
        seleccion.setVisible(true); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ColasCirculares;
    private javax.swing.JFrame ColasSimples;
    private javax.swing.JFrame ListasDobles;
    private javax.swing.JFrame ListasSimple;
    private javax.swing.JMenuItem MenuArbol;
    private javax.swing.JMenuItem MenuBinario;
    private javax.swing.JMenuItem MenuBurbuja;
    private javax.swing.JMenu MenuColas;
    private javax.swing.JMenuItem MenuHASH;
    private javax.swing.JMenuItem MenuInter;
    private javax.swing.JMenu MenuListasEnlazadas;
    private javax.swing.JMenu MenuPilas;
    private javax.swing.JMenuItem MenuSecuencia;
    private javax.swing.JFrame Pilas;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemColaCirculare;
    private javax.swing.JMenuItem jMenuItemColaSimple;
    private javax.swing.JMenuItem jMenuItemListasDoblemente;
    private javax.swing.JMenuItem jMenuItemPilas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPilasMaquina;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton jVIDEO;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

    
    
}//fin 
